import type { Check } from '../types.js';
import {
  basicAuth,
  clientCertificate,
  duplicateConnection,
  ping,
  subprotocol,
  subprotocolRefusal,
} from './connection.js';
import {
  authorize,
  bootClock,
  bootInterval,
  bootResponse,
  dataTransfer,
  heartbeat,
  meterValuesWithoutTransaction,
  statusConnector,
  statusConnector0,
  transactionIdUnique,
  transactionMeterValues,
  transactionStart,
  transactionStartReplay,
  transactionStop,
  transactionStopUnknown,
} from './core.js';
import {
  invalidPayload,
  latency,
  malformedFrame,
  malformedJson,
  serverCalls,
  singleOutstandingCall,
  unknownAction,
  unknownActionCode,
  unknownMessageType,
  unmatchedResponse,
} from './rpc.js';

/** Every OCPP 1.6-J Central System check, in execution order. */
export const OCPP16_CHECKS: readonly Check[] = [
  subprotocol,
  subprotocolRefusal,
  basicAuth,
  clientCertificate,
  ping,
  bootResponse,
  bootInterval,
  bootClock,
  heartbeat,
  statusConnector0,
  statusConnector,
  authorize,
  transactionStart,
  transactionMeterValues,
  transactionStop,
  meterValuesWithoutTransaction,
  transactionIdUnique,
  transactionStartReplay,
  transactionStopUnknown,
  dataTransfer,
  unknownAction,
  unknownActionCode,
  invalidPayload,
  malformedFrame,
  malformedJson,
  unknownMessageType,
  unmatchedResponse,
  latency,
  duplicateConnection,
  singleOutstandingCall,
  serverCalls,
];
